### ISSUE TITLE
Need to close quote

### ISSUE THREAD

**Issue by JessRudder** [halfields/sec-mens-bball#1]
[This line](https://github.com/halfields/sec-mens-bball/blob/master/lib/sec_mens_bball/scraper.rb#L14) has a quote that hasn't been closed. 

```
t.overall_record = team_table.css("#wrapper > div > main > section > div > section > div > div > div > div.panel-body > div > table > tbody > tr:nth-child(1) > td:nth-child(3)
```

As a result, the parser thinks a good deal of your file is also a quote.  You'll want to close that out and put the end `)`.

```
t.overall_record = team_table.css("#wrapper > div > main > section > div > section > div > div > div > div.panel-body > div > table > tbody > tr:nth-child(1) > td:nth-child(3)")
```

**Comment by halfields** [comment]
Quote was closed on line 14 of scraper.rb to correct syntax error.
