### ISSUE TITLE
Methods in Scraper should be class methods

### ISSUE THREAD

**Issue by JessRudder** [halfields/sec-mens-bball#2]
I believe you need to update the methods in `scraper.rb` to be class methods (by adding `self.` to the method names in the definition).

`def self.scrape_standings_page` and `def self.scrape_team_page(url)` otherwise it will complain the methods are not defined because it will be looking for class methods and you've defined instance methods.

**Comment by halfields** [comment]
Two scraper methods in scraper.rb were changed from instance methods to class methods
